[package]
name = "aimware_deobf_str"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "*", features = ["std", "derive"] }
serde_json = "*"
zydis = "*"
rayon = "*"